### ISSUE TITLE
Filtering by serviceUuids does not work correctly

### ISSUE THREAD

**Issue by ChrisScheffler** [Timeular/noble-mac#10]
After switching to noble-mac (due to Mojave) startScanning() does not filter peripherals by given serviceUuids on macOs.
```javascript
noble.startScanning(['3e135142654f9090134aa6ff5bb77046'])
```
returns any BLE peripheral in range (even those which do not provide that given serviceUUID).
The following peripheral should not be 'discovered'.
```javascript
advertisement:
   { localName: '',
     txPowerLevel: 37464576,
     manufacturerData: Buffer [Uint8Array] [ 76, 0, 16, 5, 3, 24, 170, 34, 168 ],
     serviceData: [],
     serviceUuids: []
},
```

On Linux filtering by serviceUuids works as expected.

**Comment by geovie** [comment]
Thanks for reporting! This issue is fixed in #12
