### ISSUE TITLE
installation question

### ISSUE THREAD

**Issue by ainthek** [Timeular/noble-mac#19]
Please is this installable from npm somewhere ?
or just from git ?

Any chance this will be merged with noble project or is the noble completely abandoned ?

Thank you, I have just tested git install and it seems to work.

**Comment by bankyadam** [comment]
@geovie Did you forget to publish 0.0.3 to npm?

**Comment by chrkhl** [comment]
Can someone please publish release 0.0.3 to npm? Thank you!

**Comment by jongear** [comment]
since the package isn't on npm I have been referencing it directly from git.

```json
"dependencies": {
    "noble-mac": "https://github.com/Timeular/noble-mac.git"
  },
```

**Comment by chrkhl** [comment]
> since the package isn't on npm I have been referencing it directly from git.
> 
> ```json
> "dependencies": {
>     "noble-mac": "https://github.com/Timeular/noble-mac.git"
>   },
> ```

Yes, I do the same, but I hope that there will be an npm package after all.

**Comment by keeslinp** [comment]
Are there any plans for fixing this? We're using this as a fix for a project using noble that needs to work on mojave, but part of our build process is unhappy with git dependencies. Changing this to npm would solve that problem.

**Comment by s524797336** [comment]
@keeslinp 
why not fork this project and publish a private npm package instead.
You can use @s524797336/noble-mac via `npm install @s524797336/noble-mac`, this is my fork of this project.
**But i can't make sure my version of noble-mac work on your project.**

**Comment by geovie** [comment]
FYI: noble-mac is now included in https://github.com/abandonware/noble
