### ISSUE TITLE
Advertisement.ManufacturerData comes back as unreadable buffer

### ISSUE THREAD

**Issue by jongear** [Timeular/noble-mac#21]
OS: Mojave 10.14.2
Node: 10

When attempting to access the manufacturer data of the peripheral `noble-mac` exposes a buffer. 

![image](https://user-images.githubusercontent.com/8430731/51329929-17226200-1a3c-11e9-9554-1551c19356b1.png)

stringify and utf-8 conversions return 

```
{"type":"Buffer","data":[67,0,207,25,11,9,1,0]}
<Buffer 43 00 cf 19 0b 09 01 00>
C�
```

**Comment by geovie** [comment]
That's expected. The manufacturerData is a Buffer as defined in: https://github.com/noble/noble/blob/master/README.md#peripheral-discovered 
Is the Data truncated?

**Comment by jongear** [comment]
You're correct. The data is coming back as expected and is not truncated. I was not casting properly. To find my manufacturer. In my case I neeeded `.toString('hex')`

![image](https://user-images.githubusercontent.com/8430731/51397085-0f2ef480-1b06-11e9-9aaf-9bc3af73cb90.png)
