### ISSUE TITLE
Node 10 support on linux

### ISSUE THREAD

**Issue by hannseman** [Timeular/noble-mac#23]
I understand that the main purpose of this package is to bring support for macOS Mojave but I would like to ask you if you could consider depending on https://github.com/abandonware/noble which fixes Node 10 support for linux. This is the root issue https://github.com/noble/node-bluetooth-hci-socket/issues/84.

This would enable people who have to support both macOS Mojave and Node >=10 on Linux to use this library.

**Comment by geovie** [comment]
Hi, for now I won't change from `noble/noble` to `abandonware/noble` as it is already possible to use a custom noble (`abandonware/noble` or any other) by using `noble-mac` as binding only (take a look at [index.js](https://github.com/Timeular/noble-mac/blob/master/index.js)).   
However, I'd like to integrate `noble-mac` directly in to noble, so if `abandonware/noble` is actively maintained and they're interested in Mojave support, I'm happy to create a PR.

**Comment by hannseman** [comment]
@geovie looks like `abandonware/noble` is interested in integrating. Please see https://github.com/abandonware/noble/issues/4. 

That fork is pretty popular with 1600 weekly downloads.
https://www.npmjs.com/package/@abandonware/noble

Compare that to the original package with has 1800 weekly downloads.
https://www.npmjs.com/package/noble

**Comment by rzr** [comment]
Are there any patches from this fork that are pending upstream ?

If yes they could be merged into @abandonware/noble

Again efforts to track changes are appreciated:
https://github.com/abandonware/noble/issues/2

**Comment by geovie** [comment]
@rzr No @abandonware/noble already contains the latest changes https://github.com/abandonware/noble/pull/8

**Comment by rzr** [comment]
Feel free to rebase on @abandonware/noble if you want, I plan to keep it based on upstream too
