### ISSUE TITLE
No data events after subscribing to a characteristic

### ISSUE THREAD

**Issue by keeslinp** [Timeular/noble-mac#24]
When I run `characteristic.subscribe` the callback is never called nor is the `characteristic.on('data')` fired. I am seeing a subscription event on the peripheral device so that part is working, but it does not ever call the callback or fire the event. I'm setting the data handler before calling subscribe.

I'll keep poking around and see what I can figure out.

**Comment by geovie** [comment]
Can you post a small sample of your code?
Does the 'notify' event is fired?

**Comment by keeslinp** [comment]
Well... I have no idea why but everything just started working today. My computer's bluetooth stack was probably being finicky. Thanks anyways.
