### ISSUE TITLE
Is the CleanUp method the same thing as you'd expect stop to be/do?

### ISSUE THREAD

**Issue by ghost** [Timeular/noble-mac#26]
I'm thinking about implementing a way to start and stop noble bindings, so I just wondered if you considered `CleanUp` to be equivalent to that.

`bluetooth-hci-socket` already has a `stop()` method.

**Comment by geovie** [comment]
Yes, `cleanUp` should release any native resources that are held and allows the noble (binding) instance to be GC'ed.  I'm not sure if it's already well tested, I know it works for the simple case, but I'm not sure what happens if you cleanup a binding which has a device connected.

**Comment by ghost** [comment]
So should it be renamed to `stop` to match bluetooth-hci-socket?

**Comment by geovie** [comment]
Sure I can rename it. Any other renames or additional function that would make sense? Which common interface do you have in mind?

**Comment by ghost** [comment]
Nothing  else ATM. I just saw an old noble bug re: missing stop method, and it mentioned that the bindings would need to have it first before it could be exposed at the noble level.

**Comment by geovie** [comment]
Renamed, I will create a new build soon.
