### ISSUE TITLE
Support for node version 10.15.3

### ISSUE THREAD

**Issue by lilliesAndRoses** [Timeular/noble-mac#34]
Is there any plan of adding support for node version 10.15.3?

**Comment by geovie** [comment]
@lilliesAndRoses Is it not working for you with 10.15.3?

**Comment by lilliesAndRoses** [comment]
I am getting following error while installing.

```
~/Documents/app :npm install noble-mac
npm WARN npm npm does not support Node.js v10.15.3
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
npm ERR! code E404
npm ERR! 404 Not Found: noble-mac@latest
```

**Comment by geovie** [comment]
@lilliesAndRoses I think you need to update your `npm` also be sure to add `noble-mac` as [git dependency](https://github.com/Timeular/noble-mac#installation) as it is not on npm.
You might want to try the [abandonware fork](https://github.com/abandonware/noble/) of noble, which contains `noble-mac`.

**Comment by s524797336** [comment]
@lilliesAndRoses 
Your current npm not support current node version.
Use `npm i -g npm` to update npm, you may need `sudo` for that.

**Comment by lilliesAndRoses** [comment]
Thanks. Adding a  'git dependency' worked. 
Closing the issue.
