### ISSUE TITLE
Moving forward

### ISSUE THREAD

**Issue by floating** [Timeular/noble-mac#35]
Hi all, 

I want to start out by saying thanks for this project. I'm wondering what the plan is moving forward. Do you think this should be merged back into noble or do you think it should be standalone? If standalone do you think we can have an official release on npm? As someone who needs to support newer macOS platforms I now rely on this library now instead of noble.

Thanks again!
Jordan

**Comment by s524797336** [comment]
There are no one maintained noble now. so...

**Comment by geovie** [comment]
@floating `noble-mac` is now included in [abandonware noble fork](https://github.com/abandonware/noble)    
Checkout [@abandonware/noble](https://www.npmjs.com/package/@abandonware/noble)
