### ISSUE TITLE
Native Addon does not seem to terminate

### ISSUE THREAD

**Issue by LukasBombach** [Timeular/noble-mac#41]
Hey there

if I load the compiled native node addon directly and run this little script:

```js
const util = require("util");
const { EventEmitter } = require("events");
const NobleMac = require("./native/noble_mac").NobleMac;

util.inherits(NobleMac, EventEmitter);

const nobleMac = new NobleMac();

nobleMac.init();

console.log("done");
```

The node process will never terminate. If you remove the line `nobleMac.init();` it will terminate right after logging `done`. For some reason the native process seems to keep running and I cannot find the reason nor how to terminate it.

Do you have an idea? <3

**Comment by LukasBombach** [comment]
Ok it is this line

https://github.com/Timeular/noble-mac/blob/master/src/ble_manager.mm#L18

Maybe I can find a fix and open a PR

**Comment by geovie** [comment]
@LukasBombach calling the stop method should work https://github.com/Timeular/noble-mac/blob/master/src/noble_mac.mm#L249

**Comment by LukasBombach** [comment]
OH YES

Thank you soo much! 🎉
