### ISSUE TITLE
max notification length

### ISSUE THREAD

**Issue by quinnabrvau** [Timeular/noble-mac#9]
I'm missing information from notifications. for some reason, it seems to max out at 101 bytes even when the MTU size is set higher and I send a larger amount of data
before I upgraded to Mojave and switched to noble-mac this same code worked

**Comment by geovie** [comment]
Could you try if it works with this [noble version](https://github.com/drandreas/noble)

**Comment by quinnabrvau** [comment]
regular noble works with that version but I still encounter the same problem

**Comment by geovie** [comment]
Then this is probably a change in Mojave. You can check if  the data is correct in the native part:https://github.com/Timeular/noble-mac/blob/7e286d8bd2b62205f60319fce77bbe216695f19e/src/ble_manager.mm#L228-L230

**Comment by geovie** [comment]
@quinnabrvau Any progress here? Have you checked if this is a Mojave problem?

**Comment by geovie** [comment]
@quinnabrvau I'll close this, please reopen it if this is a noble-mac issue, Thanks!

**Comment by quinnabrvau** [comment]
I don't think it is, it seems to be an issue with Mojave

**Comment by geovie** [comment]
Okay, thank you!

**Comment by AlanDZhang** [comment]
Encountered same problem here with Mojave. Mojave only accepts data with 101 bytes while my Android phone can accept larger size.

**Comment by quinnabrvau** [comment]
This appears to have been fixed in an update to Mojave, I am seeing notifications of up to 244 bytes which matches up with other OSs
